spring: 
 application:
    name: gateway-service
    
    
 config:
    import: optional:configserver:http://localhost:9999


 cloud:
    gateway:
      routes:

        - id: discovery-server
          uri: "http://localhost:8761/"
          predicates:
            - Path=/eureka 
          filters:
            - SetPath=/

 
        

            
            
        - id: customer-service
          uri: "http://localhost:8081/"
          predicates:
            - Path=/customers , /v3/api-docs/customer , /customers/*
          
          
        - id: account-service
          uri: "http://localhost:8082/"
          predicates:
            - Path=/accounts , /v3/api-docs/account ,/accounts/*

       
      default-filters:
        - TokenRelay=
   #     - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders:
#            - "Content-Type"
#            - "Authorization"
#            exposedHeaders: "*"
#            allowedMethods: "*"   
#            allowCredentials: true
#        add-to-simple-url-handler-mapping: true     
 
 server:
  servlet:
    context-path: /
    



        
        
        
        
        
        